### ISSUE TITLE
Please push a new release with fix for https://github.com/nut-tree/libnut/issues/101

### ISSUE THREAD

**Issue by lwahonen** [nut-tree/libnut#109]
Please push a release with the fix for #101. Thanks!

**Comment by s1hofmann** [comment]
Hi @lwahonen 👋 

I'm currently testing a fix to an issue, so there will be no release until this is verified.

In case you're eagerly relying on having #101 fixed, every feature/fix merged to develop triggers a snapshot release, so you could give `libnut@next` a go until a new stable release is done.
