### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/libnut#9]
Currently not all platforms properly support unicode when working with keyboard input.

**Comment by ufon** [comment]
Hi, @s1hofmann I think this is a very important feature. How we can unblock the development? Or maybe we can merge separately Unicode for Windows.
https://github.com/nut-tree/nut.js/issues/283

**Comment by s1hofmann** [comment]
Hi @ufon 👋 

I’ll be honest: The current way to unblock development is by paying me. Ever since companies started asking me for release dates and estimates I switched to mostly doing commissions. While I still love working on nut.js it’s quite disappointing to see companies giving a damn about the time and effort I put into it, while still having the audacity to ask me for release dates for bugfixes that would solve a critical issue for them.
